#Assignment-
# To apply Tf-idfvectorizer on tweets_data

#Import necessary libraries

In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from nltk.stem.porter import PorterStemmer
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.model_selection import train_test_split
import pickle
import re

#Reading data

In [ ]:
#load the dataset
import pandas as pd
df_tweets=pd.read_csv("/content/1683445294tweets.csv",encoding="ISO-8859-1")
df_tweets.head()

Unnamed: 0  X                                               text  \
0           1  1  RT @rssurjewala: Critical question: Was PayTM ...   
1           2  2  RT @Hemant_80: Did you vote on #Demonetization...   
2           3  3  RT @roshankar: Former FinSec, RBI Dy Governor,...   
3           4  4  RT @ANI_news: Gurugram (Haryana): Post office ...   
4           5  5  RT @satishacharya: Reddy Wedding! @mail_today ...   

   favorited  favoriteCount replyToSN              created  truncated  \
0      False              0       NaN  2016-11-23 18:40:30      False   
1      False              0       NaN  2016-11-23 18:40:29      False   
2      False              0       NaN  2016-11-23 18:40:03      False   
3      False              0       NaN  2016-11-23 18:39:59      False   
4      False              0       NaN  2016-11-23 18:39:39      False   

   replyToSID            id  replyToUID  \
0         NaN  8.014957e+17         NaN   
1         NaN  8.014957e+17         NaN   
2         NaN  8.014955e+17         NaN   
3         NaN  8.014955e+17         NaN   
4         NaN  8.014954e+17         NaN   

                                        statusSource       screenName  \
0  <a href="http://twitter.com/download/android" ...  HASHTAGFARZIWAL   
1  <a href="http://twitter.com/download/android" ...   PRAMODKAUSHIK9   
2  <a href="http://twitter.com/download/android" ...  rahulja13034944   
3  <a href="http://twitter.com/download/android" ...        deeptiyvd   
4  <a href="http://cpimharyana.com" rel="nofollow...        CPIMBadli   

   retweetCount  isRetweet  retweeted  
0           331       True      False  
1            66       True      False  
2            12       True      False  
3           338       True      False  
4           120       True      False

In [ ]:
df_tweets.shape

(14940, 16)

#We need only text data from dataset

In [ ]:
df_tweets.columns

Index(['Unnamed: 0', 'X', 'text', 'favorited', 'favoriteCount', 'replyToSN',
       'created', 'truncated', 'replyToSID', 'id', 'replyToUID',
       'statusSource', 'screenName', 'retweetCount', 'isRetweet', 'retweeted'],
      dtype='object')

In [ ]:
df_tweets.text.head()

0    RT @rssurjewala: Critical question: Was PayTM ...
1    RT @Hemant_80: Did you vote on #Demonetization...
2    RT @roshankar: Former FinSec, RBI Dy Governor,...
3    RT @ANI_news: Gurugram (Haryana): Post office ...
4    RT @satishacharya: Reddy Wedding! @mail_today ...
Name: text, dtype: object

#preprocessing_text

In [ ]:
## utlity function for pre-processing the text
import spacy

# load english language model and create nlp object from it
nlp = spacy.load("en_core_web_sm")

def preprocess(text):
    # remove stop words and lemmatize the text
    doc = nlp(text)
    filtered_tokens = []
    for token in doc:
        if token.is_stop or token.is_punct:
            continue
        filtered_tokens.append(token.lemma_)

    return " ".join(filtered_tokens)

In [ ]:
df_tweets['preprocessed_txt'] = df_tweets['text'].apply(preprocess)

In [ ]:
df_tweets

Unnamed: 0      X                                               text  \
0               1      1  RT @rssurjewala: Critical question: Was PayTM ...   
1               2      2  RT @Hemant_80: Did you vote on #Demonetization...   
2               3      3  RT @roshankar: Former FinSec, RBI Dy Governor,...   
3               4      4  RT @ANI_news: Gurugram (Haryana): Post office ...   
4               5      5  RT @satishacharya: Reddy Wedding! @mail_today ...   
...           ...    ...                                                ...   
14935       14936  14936  RT @saxenavishakha: Ghost of demonetization re...   
14936       14937  14937  N d modi fans-d true nationalists of the count...   
14937       14938  14938  RT @bharat_builder: Lol. Demonetization has fi...   
14938       14939  14939  RT @Stupidosaur: @Vidyut B team of BJP. CIA ba...   
14939       14940  14940  @Vidyut B team of BJP. CIA baby. CCTV, EVM but...   

       favorited  favoriteCount replyToSN              created  truncated  \
0          False              0       NaN  2016-11-23 18:40:30      False   
1          False              0       NaN  2016-11-23 18:40:29      False   
2          False              0       NaN  2016-11-23 18:40:03      False   
3          False              0       NaN  2016-11-23 18:39:59      False   
4          False              0       NaN  2016-11-23 18:39:39      False   
...          ...            ...       ...                  ...        ...   
14935      False              0       NaN  2017-04-11 14:26:38      False   
14936      False              0       NaN  2017-04-11 14:19:51       True   
14937      False              0       NaN  2017-04-11 14:19:14      False   
14938      False              0       NaN  2017-04-11 14:13:14      False   
14939      False              1    Vidyut  2017-04-11 14:13:06       True   

         replyToSID            id  replyToUID  \
0               NaN  8.014957e+17         NaN   
1               NaN  8.014957e+17         NaN   
2               NaN  8.014955e+17         NaN   
3               NaN  8.014955e+17         NaN   
4               NaN  8.014954e+17         NaN   
...             ...           ...         ...   
14935           NaN  8.518037e+17         NaN   
14936           NaN  8.518020e+17         NaN   
14937           NaN  8.518018e+17         NaN   
14938           NaN  8.518003e+17         NaN   
14939  8.516909e+17  8.518003e+17  15199808.0   

                                            statusSource       screenName  \
0      <a href="http://twitter.com/download/android" ...  HASHTAGFARZIWAL   
1      <a href="http://twitter.com/download/android" ...   PRAMODKAUSHIK9   
2      <a href="http://twitter.com/download/android" ...  rahulja13034944   
3      <a href="http://twitter.com/download/android" ...        deeptiyvd   
4      <a href="http://cpimharyana.com" rel="nofollow...        CPIMBadli   
...                                                  ...              ...   
14935  <a href="http://twitter.com/download/android" ...     MuzzammilAap   
14936  <a href="http://twitter.com/download/android" ...       JusteyAlex   
14937  <a href="http://twitter.com/download/android" ...      pavan_sethi   
14938  <a href="http://twitter.com" rel="nofollow">Tw...      Stupidosaur   
14939  <a href="http://twitter.com" rel="nofollow">Tw...      Stupidosaur   

       retweetCount  isRetweet  retweeted  \
0               331       True      False   
1                66       True      False   
2                12       True      False   
3               338       True      False   
4               120       True      False   
...             ...        ...        ...   
14935             4       True      False   
14936             0      False      False   
14937            30       True      False   
14938             2       True      False   
14939             2      False      False   

                                        preprocessed_txt  
0      RT @rssurjew

In [ ]:
df_tweets.shape

(14940, 17)

In [ ]:
#let's create the vectorizer and fit the corpus and transform them accordingly
v = TfidfVectorizer()
v.fit(df_tweets.preprocessed_txt)
transform_output = v.transform(df_tweets.preprocessed_txt)

In [ ]:
#let's print the vocabulary

print(v.vocabulary_)

{'rt': 9314, 'rssurjewala': 9310, 'critical': 3032, 'question': 8730, 'paytm': 8106, 'inform': 5512, 'demonetization': 3341, 'edict': 3838, 'pm': 8290, 'clearly': 2690, 'fishy': 4324, 'require': 9078, 'disclosure': 3547, 'amp': 1291, 'hemant_80': 5009, 'vote': 11461, 'modi': 7092, 'survey': 10380, 'app': 1409, 'roshankar': 9269, 'finsec': 4312, 'rbi': 8911, 'dy': 3772, 'governor': 4740, 'cbdt': 2450, 'chair': 2520, 'harvard': 4928, 'professor': 8524, 'lambaste': 6298, 'aam': 875, 'aadmi': 870, 'listen': 6453, 'th': 10613, 'ani_news': 1334, 'gurugram': 4829, 'haryana': 4931, 'post': 8367, 'office': 7738, 'employee': 3917, 'provide': 8567, 'cash': 2403, 'exchange': 4072, 'patient': 8074, 'hospital': 5139, 'https': 5179, 'co': 2731, 'ugmxup9': 11039, 'satishacharya': 9518, 'reddy': 8986, 'wedding': 11617, 'mail_today': 6676, 'cartoon': 2399, 'reddywedding': 8987, 'u7glnrq31f': 11014, 'derekscissors1': 3386, 'india': 5432, 'blackmoney': 2049, 'symptom': 10452, 'disease': 3558, 'hsl6ihj0qe'

In [ ]:
dir(v)

['__annotations__',
 '__class__',
 '__delattr__',
 '__dict__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getstate__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__le__',
 '__lt__',
 '__module__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__setattr__',
 '__setstate__',
 '__sizeof__',
 '__str__',
 '__subclasshook__',
 '__weakref__',
 '_char_ngrams',
 '_char_wb_ngrams',
 '_check_feature_names',
 '_check_n_features',
 '_check_params',
 '_check_stop_words_consistency',
 '_check_vocabulary',
 '_count_vocab',
 '_get_param_names',
 '_get_tags',
 '_limit_features',
 '_more_tags',
 '_parameter_constraints',
 '_repr_html_',
 '_repr_html_inner',
 '_repr_mimebundle_',
 '_sort_features',
 '_stop_words_id',
 '_tfidf',
 '_validate_data',
 '_validate_ngram_range',
 '_validate_params',
 '_validate_vocabulary',
 '_warn_for_unused_params',
 '_white_spaces',
 '_word_ngrams',
 'analyzer',
 'binary',
 'build_analyzer',

In [ ]:
#let's print the idf of each word:

all_feature_names = v.get_feature_names_out()

for word in all_feature_names:

    #let's get the index in the vocabulary
    indx = v.vocabulary_.get(word)

    #get the score
    idf_score = v.idf_[indx]

    print(f"{word} : {idf_score}")

Streaming output truncated to the last 5000 lines.
mqj9o6glwa : 9.91871721029114
mqoxhldvyo : 9.91871721029114
mr : 4.612927828904402
mr_lolwa : 8.213969118052713
mrcreepypasta0 : 9.513252102182975
mrharshal123 : 9.91871721029114
mrmitr : 9.91871721029114
mrmitron : 9.91871721029114
mrmurali_m : 9.91871721029114
mrnobre : 9.91871721029114
mrpatel1954 : 9.91871721029114
mrqo3kr6v6 : 8.414639813514865
mrs : 9.91871721029114
mrsfunnybone : 8.820104921623031
mrsgandhi : 9.91871721029114
mrtkachokra : 9.91871721029114
mrvchenna : 9.91871721029114
mrvchennai : 9.513252102182975
ms : 9.513252102182975
ms81539475 : 9.91871721029114
ms_rana : 7.0565163293616715
msa_ind : 9.91871721029114
msblairewhite : 9.91871721029114
msci : 8.53242284917125
mse : 9.91871721029114
msg : 9.513252102182975
msisodia : 7.085503866234923
msje59tohb : 9.91871721029114
mskajalaggarwal : 9.513252102182975
msm : 9.513252102182975
msmeministry : 9.91871721029114
mt6ag1zili : 9.91871721029114
mtfvb9wwgr : 9.918717210291

In [ ]:
#let's print the transformed output from tf-idf
print(transform_output.toarray())

[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
