In [132]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [133]:
ad=pd.read_csv("/content/Advertising.csv")

In [134]:
ad.head()

Unnamed: 0     TV  Radio  Newspaper  Sales
0           1  230.1   37.8       69.2   22.1
1           2   44.5   39.3       45.1   10.4
2           3   17.2   45.9       69.3    9.3
3           4  151.5   41.3       58.5   18.5
4           5  180.8   10.8       58.4   12.9

In [135]:
ad.isnull().sum()

Unnamed: 0    0
TV            0
Radio         0
Newspaper     0
Sales         0
dtype: int64

In [136]:
ad.drop(columns=["Unnamed: 0"],axis=1,inplace=True)

In [137]:
ad.head()

TV  Radio  Newspaper  Sales
0  230.1   37.8       69.2   22.1
1   44.5   39.3       45.1   10.4
2   17.2   45.9       69.3    9.3
3  151.5   41.3       58.5   18.5
4  180.8   10.8       58.4   12.9

In [138]:
ad.shape

(200, 4)

In [139]:
ad.dtypes

TV           float64
Radio        float64
Newspaper    float64
Sales        float64
dtype: object

In [140]:
# displaying the datatypes
display(ad.dtypes)

# converting 'Weight' from float to int
ad['TV'] = ad['TV'].astype(int)
ad["Radio"] = ad["Radio"].astype(int)
ad["Newspaper"] = ad["Newspaper"].astype(int)
ad["Sales"] = ad["Sales"].astype(int)
# displaying the datatypes
display(ad.dtypes)

TV           float64
Radio        float64
Newspaper    float64
Sales        float64
dtype: object

TV           int64
Radio        int64
Newspaper    int64
Sales        int64
dtype: object

In [141]:
ad.drop(columns=["TV"],axis=1,inplace=True)

In [142]:
ad.head()

Radio  Newspaper  Sales
0     37         69     22
1     39         45     10
2     45         69      9
3     41         58     18
4     10         58     12

In [143]:
## backpropogation starts===###   REGRESSION

In [144]:
df=pd.DataFrame([[39,45,10],[45,69,9],[41,58,18],[32,23,11]],columns=["radio","newspaper","sales"])

In [145]:
df

radio  newspaper  sales
0     39         45     10
1     45         69      9
2     41         58     18
3     32         23     11

In [146]:
###     intialising parameter for archtecture

In [147]:

def initialize_parameters(layer_dims):

  np.random.seed(3)
  parameters = {}
  L = len(layer_dims)

  for l in range(1, L):

    parameters['W' + str(l)] = np.ones((layer_dims[l-1], layer_dims[l]))*0.1
    parameters['b' + str(l)] = np.zeros((layer_dims[l], 1))


  return parameters


In [148]:
initialize_parameters([2,2,1])

{'W1': array([[0.1, 0.1],
        [0.1, 0.1]]),
 'b1': array([[0.],
        [0.]]),
 'W2': array([[0.1],
        [0.1]]),
 'b2': array([[0.]])}

In [149]:
# Utility Functions
def sigmoid(Z):

  A = 1/(1+np.exp(-Z))

  return A

In [150]:
def linear_forward(A_prev, W, b):

  Z = np.dot(W.T, A_prev) + b

  A = sigmoid(Z)

  return A

In [151]:
#  Main function which will forward propogation  ##
# L-layer feed forward

def L_layer_forward(X, parameters):

  A = X
  L = len(parameters) // 2                  # number of layers in the neural network

  for l in range(1, L+1):
    A_prev = A
    Wl = parameters['W' + str(l)]
    bl = parameters['b' + str(l)]
    #print("A"+str(l-1)+": ", A_prev)
    #print("W"+str(l)+": ", Wl)
    #print("b"+str(l)+": ", bl)
    #print("--"*20)

    A = linear_forward(A_prev, Wl, bl)
    #print("A"+str(l)+": ", A)
    #print("**"*20)

  return A,A_prev

In [152]:
def update_parameters(parameters,y,y_hat,A1,X):
  parameters['W2'][0][0] = parameters['W2'][0][0] + (0.0001 * (y - y_hat)*A1[0][0])
  parameters['W2'][1][0] = parameters['W2'][1][0] + (0.0001 * (y - y_hat)*A1[1][0])
  parameters['b2'][0][0] = parameters['W2'][1][0] + (0.0001 * (y - y_hat))

  parameters['W1'][0][0] = parameters['W1'][0][0] + (0.0001 * (y - y_hat)*parameters['W2'][0][0]*A1[0][0]*(1-A1[0][0])*X[0][0])
  parameters['W1'][0][1] = parameters['W1'][0][1] + (0.0001 * (y - y_hat)*parameters['W2'][0][0]*A1[0][0]*(1-A1[0][0])*X[1][0])
  parameters['b1'][0][0] = parameters['b1'][0][0] + (0.0001 * (y - y_hat)*parameters['W2'][0][0]*A1[0][0]*(1-A1[0][0]))

  parameters['W1'][1][0] = parameters['W1'][1][0] + (0.0001 * (y - y_hat)*parameters['W2'][1][0]*A1[1][0]*(1-A1[1][0])*X[0][0])
  parameters['W1'][1][1] = parameters['W1'][1][1] + (0.0001 * (y - y_hat)*parameters['W2'][1][0]*A1[1][0]*(1-A1[1][0])*X[1][0])
  parameters['b1'][1][0] = parameters['b1'][1][0] + (0.0001 * (y - y_hat)*parameters['W2'][1][0]*A1[1][0]*(1-A1[1][0]))

In [153]:
X = df[["radio","newspaper"]].values[0].reshape(2,1) # Shape(no of features, no. of training example)
y = df[["sales"]].values[0][0]

# Parameter initialization
parameters = initialize_parameters([2,2,1])

y_hat,A1 = L_layer_forward(X,parameters)
y_hat = y_hat[0][0]

update_parameters(parameters,y,y_hat,A1,X)

print('Loss for this advertising - ',-y*np.log(y_hat) - (1-y)*np.log(1-y_hat))

parameters

Loss for this advertising -  -1.201436219208424


{'W1': array([[0.10000084, 0.10000096],
        [0.10000084, 0.10000096]]),
 'b1': array([[2.14414909e-08],
        [2.14414909e-08]]),
 'W2': array([[0.10094481],
        [0.10094481]]),
 'b2': array([[0.10188982]])}

In [154]:
X = df[["radio","newspaper"]].values[0].reshape(2,1) # Shape(no of features, no. of training example)
y = df[["sales"]].values[0][0]

# Parameter initialization
parameters = initialize_parameters([2,2,1])
X

array([[39],
       [45]])

In [155]:
X = df[["radio","newspaper"]].values[0].reshape(2,1) # Shape(no of features, no. of training example)
y = df[["sales"]].values[0][0]

# Parameter initialization
parameters = initialize_parameters([2,2,1])
y

10

In [156]:
#intialize parameters
X = df[["radio","newspaper"]].values[0].reshape(2,1) # Shape(no of features, no. of training example)
y = df[["sales"]].values[0][0]

# Parameter initialization
parameters = initialize_parameters([2,2,1])
parameters

{'W1': array([[0.1, 0.1],
        [0.1, 0.1]]),
 'b1': array([[0.],
        [0.]]),
 'W2': array([[0.1],
        [0.1]]),
 'b2': array([[0.]])}

In [157]:
#calling function
X = df[["radio","newspaper"]].values[0].reshape(2,1) # Shape(no of features, no. of training example)
y = df[["sales"]].values[0][0]

# Parameter initialization
parameters = initialize_parameters([2,2,1])
L_layer_forward(X, parameters)

(array([[0.54982287]]),
 array([[0.99977518],
        [0.99977518]]))

In [158]:
#to calculate loss=(y-y_hat)   #loss for first advertising section
(y-0.54)**2

89.49160000000002

In [159]:
X = df[["radio","newspaper"]].values[0].reshape(2,1) # Shape(no of features, no. of training example)
y = df[["sales"]].values[0][0]

# Parameter initialization
parameters = initialize_parameters([2,2,1])
y_hat,A1=L_layer_forward(X, parameters)
y_hat,A1

(array([[0.54982287]]),
 array([[0.99977518],
        [0.99977518]]))

In [160]:
y_hat=y_hat[0][0]

In [161]:
A1

array([[0.99977518],
       [0.99977518]])

In [162]:
update_parameters(parameters,y,y_hat,A1,X)  ##Updating all weights and bias using formula

In [163]:
def update_parameters(parameters,y,y_hat,A1,X):#Updating all weights and bias using formula
  parameters['W2'][0][0] = parameters['W2'][0][0] + (0.0001 * (y - y_hat)*A1[0][0])
  parameters['W2'][1][0] = parameters['W2'][1][0] + (0.0001 * (y - y_hat)*A1[1][0])
  parameters['b2'][0][0] = parameters['W2'][1][0] + (0.0001 * (y - y_hat))

  parameters['W1'][0][0] = parameters['W1'][0][0] + (0.0001 * (y - y_hat)*parameters['W2'][0][0]*A1[0][0]*(1-A1[0][0])*X[0][0])
  parameters['W1'][0][1] = parameters['W1'][0][1] + (0.0001 * (y - y_hat)*parameters['W2'][0][0]*A1[0][0]*(1-A1[0][0])*X[1][0])
  parameters['b1'][0][0] = parameters['b1'][0][0] + (0.0001 * (y - y_hat)*parameters['W2'][0][0]*A1[0][0]*(1-A1[0][0]))

  parameters['W1'][1][0] = parameters['W1'][1][0] + (0.0001 * (y - y_hat)*parameters['W2'][1][0]*A1[1][0]*(1-A1[1][0])*X[0][0])
  parameters['W1'][1][1] = parameters['W1'][1][1] + (0.0001 * (y - y_hat)*parameters['W2'][1][0]*A1[1][0]*(1-A1[1][0])*X[1][0])
  parameters['b1'][1][0] = parameters['b1'][1][0] + (0.0001 * (y - y_hat)*parameters['W2'][1][0]*A1[1][0]*(1-A1[1][0]))

In [164]:
parameters#Updated all weights and bias using formula

{'W1': array([[0.10000084, 0.10000096],
        [0.10000084, 0.10000096]]),
 'b1': array([[2.14414909e-08],
        [2.14414909e-08]]),
 'W2': array([[0.10094481],
        [0.10094481]]),
 'b2': array([[0.10188982]])}

In [165]:
## third row(student) of advertising section
X = df[["radio","newspaper"]].values[1].reshape(2,1) # Shape(no of features, no. of training example)
y = df[["sales"]].values[1][0]
y_hat,A1=L_layer_forward(X, parameters)
y_hat,A1


(array([[0.57536562]]),
 array([[0.99998881],
        [0.99998881]]))

In [166]:
def update_parameters(parameters,y,y_hat,A1,X):#Updating all weights and bias using formula
  parameters['W2'][0][0] = parameters['W2'][0][0] + (0.0001 * (y - y_hat)*A1[0][0])
  parameters['W2'][1][0] = parameters['W2'][1][0] + (0.0001 * (y - y_hat)*A1[1][0])
  parameters['b2'][0][0] = parameters['W2'][1][0] + (0.0001 * (y - y_hat))

  parameters['W1'][0][0] = parameters['W1'][0][0] + (0.0001 * (y - y_hat)*parameters['W2'][0][0]*A1[0][0]*(1-A1[0][0])*X[0][0])
  parameters['W1'][0][1] = parameters['W1'][0][1] + (0.0001 * (y - y_hat)*parameters['W2'][0][0]*A1[0][0]*(1-A1[0][0])*X[1][0])
  parameters['b1'][0][0] = parameters['b1'][0][0] + (0.0001 * (y - y_hat)*parameters['W2'][0][0]*A1[0][0]*(1-A1[0][0]))

  parameters['W1'][1][0] = parameters['W1'][1][0] + (0.0001 * (y - y_hat)*parameters['W2'][1][0]*A1[1][0]*(1-A1[1][0])*X[0][0])
  parameters['W1'][1][1] = parameters['W1'][1][1] + (0.0001 * (y - y_hat)*parameters['W2'][1][0]*A1[1][0]*(1-A1[1][0])*X[1][0])
  parameters['b1'][1][0] = parameters['b1'][1][0] + (0.0001 * (y - y_hat)*parameters['W2'][1][0]*A1[1][0]*(1-A1[1][0]))

In [167]:
parameters

{'W1': array([[0.10000084, 0.10000096],
        [0.10000084, 0.10000096]]),
 'b1': array([[2.14414909e-08],
        [2.14414909e-08]]),
 'W2': array([[0.10094481],
        [0.10094481]]),
 'b2': array([[0.10188982]])}

In [168]:
## fourth row(student) of advertising section
X = df[["radio","newspaper"]].values[3].reshape(2,1) # Shape(no of features, no. of training example)
y = df[["sales"]].values[3][0]
y_hat,A1=L_layer_forward(X, parameters)
y_hat,A1

(array([[0.57516541]]),
 array([[0.99593005],
        [0.99593008]]))

In [169]:
def update_parameters(parameters,y,y_hat,A1,X):#Updating all weights and bias using formula
  parameters['W2'][0][0] = parameters['W2'][0][0] + (0.0001 * (y - y_hat)*A1[0][0])
  parameters['W2'][1][0] = parameters['W2'][1][0] + (0.0001 * (y - y_hat)*A1[1][0])
  parameters['b2'][0][0] = parameters['W2'][1][0] + (0.0001 * (y - y_hat))

  parameters['W1'][0][0] = parameters['W1'][0][0] + (0.0001 * (y - y_hat)*parameters['W2'][0][0]*A1[0][0]*(1-A1[0][0])*X[0][0])
  parameters['W1'][0][1] = parameters['W1'][0][1] + (0.0001 * (y - y_hat)*parameters['W2'][0][0]*A1[0][0]*(1-A1[0][0])*X[1][0])
  parameters['b1'][0][0] = parameters['b1'][0][0] + (0.0001 * (y - y_hat)*parameters['W2'][0][0]*A1[0][0]*(1-A1[0][0]))

  parameters['W1'][1][0] = parameters['W1'][1][0] + (0.0001 * (y - y_hat)*parameters['W2'][1][0]*A1[1][0]*(1-A1[1][0])*X[0][0])
  parameters['W1'][1][1] = parameters['W1'][1][1] + (0.0001 * (y - y_hat)*parameters['W2'][1][0]*A1[1][0]*(1-A1[1][0])*X[1][0])
  parameters['b1'][1][0] = parameters['b1'][1][0] + (0.0001 * (y - y_hat)*parameters['W2'][1][0]*A1[1][0]*(1-A1[1][0]))

In [170]:
parameters

{'W1': array([[0.10000084, 0.10000096],
        [0.10000084, 0.10000096]]),
 'b1': array([[2.14414909e-08],
        [2.14414909e-08]]),
 'W2': array([[0.10094481],
        [0.10094481]]),
 'b2': array([[0.10188982]])}

In [171]:
##Epochs implementation in oneline
# epochs implementation

parameters = initialize_parameters([2,2,1])
epochs = 5

for i in range(epochs):

  Loss = []

  for j in range(df.shape[0]):

    X = df[["radio","newspaper"]].values[j].reshape(2,1) # Shape(no of features, no. of training example)
    y = df[["sales"]].values[j][0]

    # Parameter initialization


    y_hat,A1 = L_layer_forward(X,parameters)
    y_hat = y_hat[0][0]

    update_parameters(parameters,y,y_hat,A1,X)

    Loss.append(-y*np.log(y_hat) - (1-y)*np.log(1-y_hat))

  print('Epoch - ',i+1,'Loss - ',np.array(Loss).mean())

parameters

Epoch -  1 Loss -  -2.574470124998215
Epoch -  2 Loss -  -2.969196572321615
Epoch -  3 Loss -  -3.1254168536176063
Epoch -  4 Loss -  -3.281546515191087
Epoch -  5 Loss -  -3.4375858325785664


{'W1': array([[0.10008344, 0.10006353],
        [0.10008347, 0.10006356]]),
 'b1': array([[2.56607794e-06],
        [2.56719471e-06]]),
 'W2': array([[0.12281484],
        [0.12281483]]),
 'b2': array([[0.12385578]])}

In [172]:
#By Using Keras  in same dataset  ###backpropogation ##

In [173]:
import tensorflow
from tensorflow import keras
from keras import Sequential
from keras.layers import Dense
import numpy as np
import pandas as pd

In [174]:
df=pd.DataFrame([[39,45,10],[45,69,9],[41,58,18],[32,23,11]],columns=["Radio","Newspaper","Sales"])

In [175]:
df

Radio  Newspaper  Sales
0     39         45     10
1     45         69      9
2     41         58     18
3     32         23     11

In [176]:
model=Sequential()
model.add(Dense(2,activation="linear",input_dim=2))
model.add(Dense(1,activation="linear"))

In [177]:
model.summary()

Model: "sequential_2"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense_4 (Dense)             (None, 2)                 6         
                                                                 
 dense_5 (Dense)             (None, 1)                 3         
                                                                 
Total params: 9
Trainable params: 9
Non-trainable params: 0
_________________________________________________________________


In [178]:
model.get_weights()

[array([[-0.5197842,  0.3702891],
        [ 1.0393742,  0.8370913]], dtype=float32),
 array([0., 0.], dtype=float32),
 array([[ 0.71172845],
        [-1.3318883 ]], dtype=float32),
 array([0.], dtype=float32)]

In [179]:
new_weights=[np.array([[0.1,0.1],
        [0.1,0.1]], dtype=np.float32),
np.array([0., 0.], dtype=np.float32),
np.array([[0.1],
        [0.1]], dtype=np.float32),
np.array([0.], dtype=np.float32)]

In [180]:
model.set_weights(new_weights)

In [181]:
model.get_weights()

[array([[0.1, 0.1],
        [0.1, 0.1]], dtype=float32),
 array([0., 0.], dtype=float32),
 array([[0.1],
        [0.1]], dtype=float32),
 array([0.], dtype=float32)]

In [182]:
optimizer=keras.optimizers.Adam(learning_rate=0.001)
model.compile(loss="mean_squared_error",optimizer=optimizer)

In [183]:
model.get_weights()

[array([[0.1, 0.1],
        [0.1, 0.1]], dtype=float32),
 array([0., 0.], dtype=float32),
 array([[0.1],
        [0.1]], dtype=float32),
 array([0.], dtype=float32)]

In [184]:
#stop

In [185]:
#### CLASSIFICATION  on same data only sales will be in the form of 0 or 1