In [ ]:
import numpy as np
import tensorflow as tf
import matplotlib .pyplot as plt

In [ ]:
y_predicted=np.array([1,1,0,0,1])
y_true=np.array([0.30,0.7,1,0,0.5])

In [ ]:
#mean absoulute error function
def mae(y_true,y_predicted):
  total_error=0
  for yt,yp in zip(y_true,y_predicted):
    print(yt,yp)


In [ ]:
mae(y_true,y_predicted)

0.3 1
0.7 1
1.0 0
0.0 0
0.5 1


In [ ]:
def mae(y_true,y_predicted):
  total_error=0
  for yt,yp in zip(y_true,y_predicted):
   total_error+=abs(yt-yp)     #absolute difference between yt and yp using 'abs' function
   print ("Total Error:",total_error)
   mae=total_error/len(y_true)
   return mae


In [ ]:
mae(y_true,y_predicted)

Total Error: 0.7


0.13999999999999999

In [ ]:
def mae(y_true,y_predicted):
  total_error=0
  for yt,yp in zip(y_true,y_predicted):
   total_error+=abs(yt-yp)     #absolute difference between yt and yp using 'abs' function
   print ("Total Error:",total_error)
   mae=total_error/len(y_true)
   print("MAE:",mae)
   return mae

In [ ]:
mae(y_true,y_predicted)

Total Error: 0.7
MAE: 0.13999999999999999


0.13999999999999999

In [ ]:
np.sum(np.abs(y_predicted-y_true))#total error

2.5

In [ ]:
np.abs(y_predicted-y_true)

array([0.7, 0.3, 1. , 0. , 0.5])

In [ ]:
np.mean(np.abs(y_predicted-y_true))  #one line function using numpy.

0.5

In [ ]:
###  Log function
np.log(0.0000000001)

-23.025850929940457

In [ ]:
epsilon=1e-15

In [ ]:
y_predicted

array([1, 1, 0, 0, 1])

In [ ]:
y_predicted_new=[max(i,epsilon)for i in y_predicted]#list comprehension
y_predicted_new

[1, 1, 1e-15, 1e-15, 1]

In [ ]:
y_predicted_new=[min(i,1-epsilon)for i in y_predicted]
y_predicted_new

[0.999999999999999, 0.999999999999999, 0, 0, 0.999999999999999]

In [ ]:
y_predicted_new=np.array(y_predicted)
np.log(y_predicted_new)

<ipython-input-17-e401df9c1d81>:2: RuntimeWarning: divide by zero encountered in log
  np.log(y_predicted_new)


array([  0.,   0., -inf, -inf,   0.])

In [ ]:
##  log loss formula=logloss or binary entropy
-np.mean(y_true*np.log(y_predicted_new)+(1-y_true)*np.log(1-y_predicted_new))

<ipython-input-18-de106cb783e1>:2: RuntimeWarning: divide by zero encountered in log
  -np.mean(y_true*np.log(y_predicted_new)+(1-y_true)*np.log(1-y_predicted_new))
<ipython-input-18-de106cb783e1>:2: RuntimeWarning: invalid value encountered in multiply
  -np.mean(y_true*np.log(y_predicted_new)+(1-y_true)*np.log(1-y_predicted_new))


nan

In [ ]:
def log_loss(y_true,y_predicted):
  epsilon=1e-15
  y_predicted_new=[max(i,epsilon)for i in y_predicted]
  y_predicted_new=[min(i,1-epsilon)for i in y_predicted_new]
  y_predicted_new=np.array(y_predicted_new)
  return -np.mean(y_true*np.log(y_predicted_new)+(1-y_true)*np.log(1-y_predicted_new))


In [ ]:
log_loss(y_true,y_predicted)

17.2696280766844