In [36]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.neighbors import KNeighborsClassifier#KNN method
from sklearn.model_selection import train_test_split,cross_val_score
from sklearn.preprocessing import StandardScaler
from sklearn.datasets import load_iris#Dataset(descret dataset) perfect dataset classification model
%matplotlib inline

In [37]:
data=load_iris

In [38]:
flowers=load_iris()

In [39]:
print(flowers.DESCR)

.. _iris_dataset:

Iris plants dataset
--------------------

**Data Set Characteristics:**

    :Number of Instances: 150 (50 in each of three classes)
    :Number of Attributes: 4 numeric, predictive attributes and the class
    :Attribute Information:
        - sepal length in cm
        - sepal width in cm
        - petal length in cm
        - petal width in cm
        - class:
                - Iris-Setosa
                - Iris-Versicolour
                - Iris-Virginica
                
    :Summary Statistics:

    ============== ==== ==== ======= ===== ====================
                    Min  Max   Mean    SD   Class Correlation
    ============== ==== ==== ======= ===== ====================
    sepal length:   4.3  7.9   5.84   0.83    0.7826
    sepal width:    2.0  4.4   3.05   0.43   -0.4194
    petal length:   1.0  6.9   3.76   1.76    0.9490  (high!)
    petal width:    0.1  2.5   1.20   0.76    0.9565  (high!)
    ============== ==== ==== ======= ===== ===========

In [40]:
### Load _iris(properties)

In [41]:
flowers.data[:5,:]

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2]])

In [42]:
flowers.feature_names

['sepal length (cm)',
 'sepal width (cm)',
 'petal length (cm)',
 'petal width (cm)']

In [43]:
flowers.target[:100]

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [44]:
flowers.data.shape

(150, 4)

In [45]:
flowers.target_names

array(['setosa', 'versicolor', 'virginica'], dtype='<U10')

In [46]:

flowers.data[100]

array([6.3, 3.3, 6. , 2.5])

In [47]:
df = pd.DataFrame(flowers.data, columns = flowers.feature_names)

In [48]:
df.head()

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0                5.1               3.5                1.4               0.2
1                4.9               3.0                1.4               0.2
2                4.7               3.2                1.3               0.2
3                4.6               3.1                1.5               0.2
4                5.0               3.6                1.4               0.2

In [49]:

flowers.target[100]

2

In [50]:
# Create X and y.

X, y = flowers.data, flowers.target

In [51]:
# Train/Test Split.
X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.20,
    random_state=42,
    stratify=y
)

In [52]:
# Instantiate support vector machine.
from sklearn.svm import LinearSVC, SVC
svc = SVC()

In [53]:
# Fit support vector machine to training data.
svc.fit (X_train,y_train)

SVC()

In [54]:
svc.score(X_train,y_train)

0.9833333333333333

In [55]:
svc.score(X_test,y_test)

0.9666666666666667

In [56]:
# Generate predictions.
y_pred = svc.predict(X_test)

In [57]:
# Measure performance based on accuracy.

from sklearn.metrics import accuracy_score

In [58]:
accuracy_score(y_test,y_pred)

0.9666666666666667

### Hyperparameters for svm

In [59]:
# Instantiate SVM.

svc = SVC (

    C = 100,
    kernel = "rbf",
    gamma = "scale"
)

# Fit on training data.

svc.fit(X_train, y_train)

# Evaluate model.

# accuracy_score(y_test, svc.predict(X_test))

SVC(C=100)

In [60]:
svc.score(X_train,y_train)

0.9916666666666667

In [61]:
svc.score(X_test,y_test)

0.9666666666666667

In [62]:
#import pandas
import pandas as pd

# Create DataFrame with column for predicted values.

results = pd.DataFrame(svc.predict(X_test), columns =['predicted'])

# Create column for observed values.
results['actual'] = y_test

In [63]:
# Check out first five rows.
results.head()

predicted  actual
0          0       0
1          2       2
2          1       1
3          1       1
4          0       0